"""Stimulus generation: random-dot stereograms and rendered scenes.

Scenes sit *beside* L1 rather than inside it. L1 (`geometry`) is the generative
model the framework reasons with; `scenes` is the ground truth the framework is
evaluated against. Keeping them separate is what makes an evaluation meaningful:
if the stimulus were generated by the same code path the estimator inverts, a
perfect score would prove nothing. See ADR-0006.
"""

from activestereo.scenes.base import Scene, StereoStimulus
from activestereo.scenes.depthmaps import (
    corrugated,
    disk,
    slanted_plane,
    staircase,
)
from activestereo.scenes.rds import RandomDotStereogram, render_rds

__all__ = [
    "RandomDotStereogram",
    "Scene",
    "StereoStimulus",
    "corrugated",
    "disk",
    "render_rds",
    "slanted_plane",
    "staircase",
]
